version: '3.8'

services:
  app:
    build: ./app
    container_name: local-app
    ports:
      - "5000:5000"
    environment:
      - VERSION=${VERSION:-1.0}
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge